import Head from 'next/head'

export default function Home(){
const handleSubmit=(e) =>{
    e.preventDefault();
}
    return(
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width,initial-scale=1"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <form onSubmit={handleSubmit}>
                <input type="text"/>
                <button type='submit'>Send</button>
                </form>
                <ul>
                    <li>Hi</li>
                    <li>There</li>
                </ul>
            </main>
        </>
    );
}